#!/bin/bash
## Assuming all your file are named as *FileN.txt* and so on
endresult="$( awk '{print $1 "\t" $2}'  File1.txt )"
for file in F*.txt
do 

    endresult=$( paste <( echo "$endresult" ) <( awk '{ if(length($3) != 0) { print $3 }else{print 0}}'  $file ) ) 

done

#Replacing empty values for zeroes
endresult=$( echo "$endresult" | awk -v max_rows=$( echo "$endresult" | awk '{print NF}' | sort -r | head -1 ) 'BEGIN{ OFS="\t" }{ for(i=1;i < (max_rows + 1);i++) {  if(length($i) == 0 ){  $i = 0 } } ; print $0}' ) 
