#!/bin/bash --norc

desthost=valkyrie.3111skyline.com
excl='--exclude=.~* --exclude=*.class'

usage() {       ## simple usage function to display usage
cat >&2 << USG

  usage: ${0##*/} [[-n|--dry-run|'options'] src [dest (~/Documents)]

for  

  rsync [-uai[n]]'options' \$src ${desthost}:\$dest [${desthost}:~/Documents]

USG

    exit 0
}

## test for '-h' or '--help'
[ -z "$1" ] || [[ "${1:0:3}" =~ '-h' ]] && usage

## test for additional options passed to rsync
if test "${1:0:1}" == '-'; then

  # options present so src is $2, dest is $3
  src="$2"
  destfn=${3:-~/Documents}
  dest="${desthost}:${destfn}"

  # preserve '-n' capability for '-uain' test
  if test "$1" == '-n' || test "$1" == '--dry-run'; then
    echo "[DRY RUN]"
    opts='-uain'
  else
    # use options supplied for rsync
    opts="$1"
  fi

else

  # default use
  src="$1"
  destfn=${2:-~/Documents}
  dest="${desthost}:${destfn}"
  opts='-uai'

fi

## output the text of the comman executed
echo "rsync $opts $excl ${src} ${dest}"

if [[ "$src" =~ '*' ]]; then
  rsync $opts $excl ${src} "${dest}"   # allow file globbing expansion
else
  rsync $opts $excl "${src}" "${dest}"
fi
