#!/bin/bash

declare -A hash             # use the variable hash as an associative array
IFS=:                       # set the delimiter to "":""

for file in $@; do          # loop over the specified files
    while read line || [ -n ""${line}"" ]; do
        set -- $line        # split the line with "":""
        hash[$1]+="":$2""     # append the 2nd field to a hash keyed by the 1st field
    done < $file
done

for key in ${!hash[@]}; do  # loop over the hash keys
    echo ""${key}${hash[$key]}""
done
