#!/bin/bash

# This gives an infinite loop
while :
do
    echo ""Please enter your first name: ""
    # Changed NAME to name, uppercase can clash with shell variables
    read name

    # This breaks out of the infinite loop when the user hits <RETURN>
    [[ -z $name ]] && break

    # Note that I have changed the patterns to what I think you mean
    case $name in
        [a-hA-H]*) echo ""$name, you are in group 10""
        ;;
        [i-mI-M]*) echo ""$name, you are in group 20""
        ;;
        [n-qN-Q]*) echo ""$name, you are in group number 30""
        ;;
        [r-zR-Z]*) echo ""$name, you are in group number 40""
        ;;
        *) echo ""Please enter valid input!""
        ;;
    esac
done
echo ""Goodbye!""
