#!/bin/bash

main()
{
   set -x
   local BIN_PATH CertType Password Commonname 
   BIN_PATH=""keytool""
   # add commas between the long options
   if ! options=$(getopt -u -o t:p:c: -l certtype:,password:,commonname: -- ""$@"")
      then
      # something went wrong, getopt will put out an error message for us
         echo ""Error on parsing parameters""
         exit 1
   fi  

   set -- $options

   while [ $# -gt 0 ] 
   do
      case ""$1"" in
       -t | --certtype) CertType=""$2"" ; shift;;
       -p | --password) Password=""$2"" ; shift;;
       -c | --commonname) Commonname=""$2"" ;shift;;
       -- ) shift; break;;
       -* ) echo ""$0: error - unrecognized option $1"" 1>&2; exit 1;; 
       *  ) break;;
      esac
      shift
   done

   echo ""Cert type is: $CertType""
   # correct the two variable names below
   echo ""Password is: $Password""        # was $KeystorePassword
   echo ""common name is: $Commonname""   # was $CommonName
}
main ""$@""
