#!/usr/bin/env bash

file=/tmp/egz.txt

# Creating example file
echo ""First Line"" > $file
echo ""Second line"" >> $file
echo ""Third Line"" >> $file
echo ""Some other line"" >> $file

sed_pattern=""s|Some other line|Fourth Line|g""

sed -i ""s|Some other line|Fourth Line|g"" $file

if [[ $? -eq 0 ]]; then
    echo ""Sed with pattern works properly.""
else
    echo ""Sed with pattern works incorrect.""
fi

sed -i ""${sed_pattern}"" $file

if [[ $? -eq 0 ]]; then
    echo ""Sed with pattern from variable works properly.""
else
    echo ""Sed with pattern from variable works incorrect.""
fi
