#!/usr/bin/bash

# /mnt/Vancouver/Programming/scripts/cron_notification.sh

# For use with crontab [ sudo gedit /etc/crontab ]
# cron (Arch Linux: cronie) requires full paths:
#   /usr/bin/aplay
#   /usr/bin/notify-send

for i in 1 2 3 4 5
  do
    #aplay alarm.mp3    ## << aplay cannot play MP3 files; use WAV
    # ----------------------------------------
    # NEEDED TO RUN 'aplay' FROM crontab:
    # https://unix.stackexchange.com/questions/231941/cant-run-aplay-as-root
    # https://www.reddit.com/r/linuxquestions/comments/37vcbo/playing_audio_from_a_cronjob/
    # PulseAudio needs XDG_RUNTIME_DIR, so:

    XDG_RUNTIME_DIR=/run/user/`id -u` /usr/bin/aplay /mnt/Vancouver/Programming/scripts/PHASER.WAV
    # ----------------------------------------
    sleep 0.25
done

# ----------------------------------------------------------------------------
# ""Critical"" alerts persist until clicked (i.e., do not appear, then fade after ~20""):
# notify-send -u critical 'Hello Victoria!' 'Countdown has ended!' --icon=dialog-information

/usr/bin/notify-send -u critical 'Hello Victoria!' ""It's 3 pm!"" -i /mnt/Vancouver/Programming/scripts/alert.jpg
