#!/bin/bash

dmg_path="$1"

# use process redirection to capture the mount point and dev entry
IFS=$'\n' read -rd '\n' mount_point dev_entry < <(
    # mount the diskimage; leave out -readonly if making changes to the filesystem
    hdiutil attach -readonly -plist "$dmg_path" | \

    # convert output plist to json
    plutil -convert json - -o - | \

    # extract mount point and dev entry
    jq -r '
        .[] | .[] |
        select(."volume-kind" == "hfs") |
        ."mount-point" + "\n" + ."dev-entry"
    '
)

# work with the zip file
ls "$mount_point/*.zip"

# unmount the disk image
hdiutil detach "$dev_entry"
