#!/bin/bash

cmd() {
    trap '' INT
    trap 'echo ""Signal USR1 received (pid=$BASHPID)""; EXIT=1' USR1
    EXIT=0
    while [ $EXIT -eq 0 ]
    do
        echo ""Starting (pid=$BASHPID)...""
        sleep 5 # represents ""wine theprogram""
        echo ""theprogram killed or finished""
        date
        echo ""Exit code $?""
        if [ $EXIT -eq 0 ]; then
            echo ""Sleeping for 2 seconds, then restarting theprogram...""
            sleep 2
        fi
    done
    echo ""Exiting (pid=$BASHPID)""
}

run() { cmd & PID=$!; echo Started $PID; }
graceful_exit() { kill -s USR1 $PID && echo ""$PID signalled to exit (USR1)""; }
shutdown() { kill -0 $PID 2>/dev/null && echo ""Unexpected exit, killing $PID"" && kill $PID; }

trap 'graceful_exit' INT
trap 'shutdown' EXIT
run

while :
do
    wait && break
done

echo ""Exiting monitor process""
