#!/bin/bash
trap ''2
title=""////////////////////
10101010101010101010
///main user menu///
10101010101010101010
////////////////////
""
clear
echo ""$title""
courseworkfiles=""/home/hiphappy1/Documents/CourseworkFiles""
PS3='Select option: '
choice=(""Create User"" ""Edit User"" ""Remove User"" ""Exit"")
finished=0
while (( !finished )); do
    select cho in ""${choice[@]}""
    do
        case $cho in
            ""Create User"")
                ""$courseworkfiles/CreateUser.sh""
                break
                ;;
            ""Edit User"")
                ""$courseworkfiles/EditUser.sh""
                break
                ;;
            ""Delete User"")
                ""$courseworkfiles/RemoveUser.sh""
                break
                ;;
            ""Exit"")
                finished=1
                break
                ;;
            *)
                echo ""ERROR try again""
                ;;
        esac
    done
done
